---
title: "Week12_Tasks"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(magrittr)
library(dplyr)
library(readr)
library(tm)
library(jiebaR)
library(wordcloud2)
TXT = NULL
```

```{r TW_VC}
CSB <- list.files(path = "/Users/good.eddy/Downloads/twP/Chen_Shui_Bian" ,pattern=".txt")
setwd("/Users/good.eddy/Downloads/twP/Chen_Shui_Bian")
CSBdf = NULL
for(i in 1:length(CSB)){
  CSBdf[i] <- read_file(CSB[i])
}
CSBdf <- gsub("\n", "", CSBdf)
CSBdf <- gsub("\r", "", CSBdf)


CCK <- list.files(path = "/Users/good.eddy/Downloads/twP/Chiang_Ching_Kuo" ,pattern=".txt")
setwd("/Users/good.eddy/Downloads/twP/Chiang_Ching_Kuo")
CCKdf = NULL
for(i in 1:length(CSB)){
  CCKdf[i] <- read_file(CCK[i])
}
CCKdf <- gsub("\n", "", CCKdf)
CCKdf <- gsub("\r", "", CCKdf)


CKS <- list.files(path = "/Users/good.eddy/Downloads/twP/Chiang_Kai_Shek" ,pattern=".txt")
setwd("/Users/good.eddy/Downloads/twP/Chiang_Kai_Shek")
CKSdf = NULL
for(i in 1:length(CKS)){
  CKSdf[i] <- read_file(CKS[i])
}

CKSdf <- gsub("\n", "", CKSdf)
CKSdf <- gsub("\r", "", CKSdf)

LDH <- list.files(path = "/Users/good.eddy/Downloads/twP/Lee_Deng_Hui" ,pattern=".txt")
setwd("/Users/good.eddy/Downloads/twP/Lee_Deng_Hui")
LDHdf = NULL
for(i in 1:length(LDH)){
  LDHdf[i] <- read_file(LDH[i])
}

LDHdf <- gsub("\n", "", LDHdf)
LDHdf <- gsub("\r", "", LDHdf)

MYJ <- list.files(path = "/Users/good.eddy/Downloads/twP/Ma_Ying_Ju" ,pattern=".txt")
setwd("/Users/good.eddy/Downloads/twP/Ma_Ying_Ju")
MYJdf = NULL
for(i in 1:length(MYJ)){
  MYJdf[i] <- read_file(MYJ[i])
}

MYJdf <- gsub("\n", "", MYJdf)
MYJdf <- gsub("\r", "", MYJdf)
```

```{r CSB}
seq <- worker(stop_word ="/Volumes/BaseQi/W12/tm.tutorial2/stop_words.txt")
CSB <- seq[CSBdf]
length(CSB)
CSB <- CSB %>%
  freq %>%
  arrange(desc(freq)) 
colnames(CSB) <- c("Word","Freq")
wordcloud2(CSB, size = 1.3)

```

```{r CKS}
CKS <- seq[CKSdf]
length(CKS)
CKS <- CKS %>%
  freq %>%
  arrange(desc(freq)) 
colnames(CKS) <- c("Word","Freq")
wordcloud2(CKS, size = 1.3)
```

```{r LDH}
LDH <- seq[LDHdf]
length(LDH)
LDH <- LDH %>%
  freq %>%
  arrange(desc(freq)) 
colnames(LDH) <- c("Word","Freq")
wordcloud2(LDH, size = 1.3)
```

```{r CCK}
CCK <- seq[CCKdf]
length(CCK)
CCK <- CCK %>%
  freq %>%
  arrange(desc(freq)) 
colnames(CCK) <- c("Word","Freq")
wordcloud2(CCK, size = 1.3)
```

```{r MYJ}
MYJ <- seq[MYJdf]
length(MYJ)
MYJ <- MYJ %>%
  freq %>%
  arrange(desc(freq)) 
colnames(MYJ) <- c("Word","Freq")
wordcloud2(MYJ, size = 1.3)
```
